### ISSUE TITLE
No Team ID Found

### ISSUE THREAD

**Issue by thomashaury** [ivRodriguezCA/RE-iOS-Apps#5]
<img width="561" alt="Screen Shot 2019-07-15 at 6 06 57 PM" src="https://user-images.githubusercontent.com/14005623/61258625-716e5800-a72b-11e9-932d-8da28cb12acc.png">

Let me just say this tutorial is great so far.

I'm on iOS12.0 and get this error. Anyone know how to get past this?

**Comment by ivRodriguezCA** [comment]
Thanks for reading and your feedback!

Try using [`frida-ios-dump`](https://github.com/AloneMonkey/frida-ios-dump) instead of `bfinject`. The injection is not working on iOS 12 thus the error you're getting. `frida-ios-dump` uses [Frida](https://www.frida.re/docs/ios/) to launch the application and then dump it.

**Comment by ivRodriguezCA** [comment]
Here are some steps on how to setup and use `frida-ios-dump`: https://ivrodriguez.com/decrypting-ios-applications-ios-12-edition/

Feel free to re-open the issue if this doesn't work for you. Thanks again for reading!
